name: run rostest inside docker

on:
    schedule:
        - cron: '30 0 * * *'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  docker_build:
    name: test docker build
    runs-on: ubuntu-latest
    steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
              driver: docker
        - name: build
          uses: docker/build-push-action@v2
          with:
              push: false
              tags: detic_ros:latest
              build_args: INSTALL_JSK_PCL=false
        - name: rostest
          run: |
              docker run --rm detic_ros:latest /bin/bash -i -c "source ~/.bashrc; rostest detic_ros test_node.test"
