name: run rostest inside docker

on:
    schedule:
        - cron: '30 0 * * *'
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  docker_build:
    name: test docker build
    runs-on: ubuntu-latest
    steps:
        - name: Free disk space
          run: |
            sudo rm -rf "/opt/ghc" || true
            sudo rm -rf "/usr/share/dotnet" || true
            sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
            sudo rm -rf "/usr/local/lib/android" || true
            sudo rm -rf "/usr/local/share/boost" || true
            sudo apt purge -y \
              ansible* \
              aria2* \
              aspnetcore* \
              azure-cli* \
              cabal* \
              clang* \
              dotnet-* \
              firefox* \
              gfortran-* \
              ghc* \
              google-chrome-stable* \
              google-cloud-sdk* \
              imagemagick* \
              javascript* \
              kubectl* \
              llvm* \
              mono* \
              mysql* \
              nginx* \
              node* \
              npm* \
              nuget* \
              php* \
              postgresql* \
              powershell* \
              rpm* \
              ruby* \
              sqlite3* \
              subversion \
              temurin* \
              tmux* \
              vim* \
              yarn*
            sudo apt-get autoremove -y >/dev/null 2>&1 || true
            sudo apt-get autoclean -y >/dev/null 2>&1 || true
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with:
              driver: docker
        - name: build
          uses: docker/build-push-action@v2
          with:
              push: false
              tags: detic_ros:latest
              build-args: | # for testing purposes only
                INSTALL_JSK_PCL=false
                KEEP_LAUNCH_FILES=true
        - name: rostest
          run: |
              docker run --rm detic_ros:latest /bin/bash -i -c "source ~/.bashrc; rostest detic_ros test_node.test"
